services:
  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile.dev
    env_file: .env
    volumes:
      - .:/app
      - ../bioreport/storage/app/uploaded_documents:/app/files:ro
    networks:
      - bioreport

networks:
  bioreport:
    driver: bridge

volumes:
  postgres_data:
